### ISSUE TITLE
problem configuring ExUnit

### ISSUE THREAD

**Issue by luismackmack** [smoku/phoenix_api_docs#10]
As indicated in the documentation, i put in the test_helper.exs this:

`PhoenixApiDocs.start
ExUnit.start(formatters: [ExUnit.CLIFormatter, PhoenixApiDocs.Formatter])
`

when i run **mix test**, the console show me this:

`09:22:51.173 [error] GenEvent handler PhoenixApiDocs.Formatter installed in #PID<0.323.0> terminating
** (UndefinedFunctionError) function WhitespaceEx.Application.Router.__routes__/0 is undefined (module WhitespaceEx.Application.Router is not available)
    WhitespaceEx.Application.Router.__routes__()
    (phoenix_api_docs) lib/phoenix_api_docs/generator.ex:26: PhoenixApiDocs.Generator.routes_docs/2
    (phoenix_api_docs) lib/phoenix_api_docs/generator.ex:12: PhoenixApiDocs.Generator.run/0
    (phoenix_api_docs) lib/phoenix_api_docs/formatter.ex:22: PhoenixApiDocs.Formatter.save_blueprint_file/0
    (phoenix_api_docs) lib/phoenix_api_docs/formatter.ex:9: PhoenixApiDocs.Formatter.handle_event/2
    (stdlib) gen_event.erl:573: :gen_event.server_update/4
    (stdlib) gen_event.erl:555: :gen_event.server_notify/4
    (stdlib) gen_event.erl:296: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:suite_finished, 6679713, nil}
`

and the documentation in a file api.apib is not generate. The project configuration has erlang 19.2, elixir 1.4.2, Phoenix v1.2.4, nodejs 7.4.0, Erlang/OTP 20

**Comment by luismackmack** [comment]
i had to downgrade Erlang/OTP 20 to Erlang/OTP 19 for make it run
